spring:
  application:
      name: SpringbootStarterTemplate

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${SUBA_USERNAME:myusername}
    password: ${SUBA_PASSWORD:mypassword}
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: ${JPA_SHOWSQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMATSQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: jamalyuosef000@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.mail: DEBUG

application:
  security:
    jwt:
      secret-key:  ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 1d
      refresh-expiration: 604800000 # refresh token — 7 days
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:8080/auth/oauth2/callback}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
