spring:
  application:
      name: SpringbootStarterTemplate



management:
  info:
    env:
      enabled: true

info:
  app:
    name: Spring Boot Starter Template
    description: Production-ready starter template
    version: 1.0.0
