spring:
  application:
      name: SpringbootStarterTemplate
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}        # active profile is "dev" switching to prod needs to handle prod.yml first

resend:
  api-key: ${RESEND_API_KEY}

management:
  info:
    env:
      enabled: true

info:
  app:
    name: Spring Boot Starter Template
    description: Production-ready starter template
    version: 1.0.0
